Better err msg os release
topgrade-rs/topgrade pull request #511
Opened 2023-07-22 20:38 UTC by 6543

closes  #499

- bump rust-ini get rid of the panic
- detect if something is wrong with os-release

2023-07-22 20:57 UTC, 6543 commented
![2023-07-22_22-56](https://github.com/topgrade-rs/topgrade/assets/24977596/a17be757-315c-460e-a778-b8db9ca6cde4)

2023-07-23 06:46 UTC, SteveLauC requested changes

2023-07-23 06:46 UTC, SteveLauC commented on src/error.rs
> +    #[error("File \"/etc/os-release\" do not exist or is empty")]
#[error("File \"/etc/os-release\" does not exist or is empty")]

2023-07-23 06:48 UTC, SteveLauC commented
Except for that little grammar mistake, this PR LGTM, thanks! :)

2023-07-23 15:10 UTC, 6543 commented on src/error.rs
> +    #[error("File \"/etc/os-release\" do not exist or is empty")]
```suggestion
    #[error("File \"/etc/os-release\" does not exist or is empty")]
```

2023-07-23 15:12 UTC, 6543 commented
Done :)

As pulls are squash merged i did just append the commit.
If i have to swuash them tell me

@SteveLauC 🚀

2023-07-24 00:26 UTC, SteveLauC approved these changes

2023-07-24 00:27 UTC, merged