Added an Audit step for FreeBSD and DragonFly packagees.
topgrade-rs/topgrade pull request #640
Opened 2024-01-07 16:49 UTC by wolpert

Allows for auditing the packages to be disabled since they are breaking steps. Current behaivor is the default, where if the audit fails topgrade stops. Can be disabled in the [misc] section independenly from other sections.

Probably we should have a document explaining all the Steps in the system. Maybe as a separate PR?

This is a potential fix for the bug I reported here: https://github.com/topgrade-rs/topgrade/issues/639

## Standards checklist:

- [X] The PR title is descriptive.
- [X] I have read `CONTRIBUTING.md`
- [X] The code compiles (`cargo build`)
- [X] The code passes rustfmt (`cargo fmt`)
- [X] The code passes clippy (`cargo clippy`)
- [X] The code passes tests (`cargo test`)
- [X] *Optional:* I have tested the code myself
 
## For new steps
- [X] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

2024-01-07 16:53 UTC, wolpert commented
BTW, tested in FreeBSD.

With default configuration file, there is no change in behavior.

When the following is added to the configuration file, the Audit step is removed.
```toml
[misc]
disable = ["audit"]
```

2024-01-08 00:55 UTC, SteveLauC requested changes
Hi, thanks for this patch!

If you want to make audit a step, you should also call `print_separator()` in that function:

```diff
pub fn audit_packages(ctx: &ExecutionContext) -> Result<()> {
    let sudo = require_option(ctx.sudo().as_ref(), REQUIRE_SUDO.to_string())?;
    
    print_separator("FreeBSD Audit");
    
    Command::new(sudo)
        .args(["/usr/sbin/pkg", "audit", "-Fr"])
        .status_checked()
}
```

2024-01-08 01:34 UTC, SteveLauC commented on src/steps/os/dragonfly.rs
> +    print_separator("DragonFly BSD Packages");
```suggestion
    print_separator("DragonFly BSD Audit");
```

2024-01-08 01:34 UTC, wolpert commented
> If you want to make audit a step, you should also call `print_separator()` in that function:

Good idea. Just updated with the change to both FreeBSD and DragonFly. Thanks!

2024-01-08 01:37 UTC, SteveLauC approved these changes
Thanks!

2024-01-08 01:40 UTC, merged