Extra options for distrobox
topgrade-rs/topgrade pull request #83
Opened 2022-10-27 17:02 UTC by LeSnake04

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

2022-10-27 17:11 UTC, LeSnake04 commented
@DottoDev

2022-10-27 20:06 UTC, DottoDev requested changes
Missing one attribute, if that's fixed it will be approved.

2022-10-27 20:06 UTC, DottoDev commented on src/config.rs
> +#[serde(deny_unknown_fields)]
missing #[allow(clippy::upper_case_acronyms)]

2022-10-27 22:08 UTC, LeSnake04 commented on src/config.rs
> +#[serde(deny_unknown_fields)]
done

2022-10-27 22:29 UTC, DottoDev approved these changes

2022-10-27 22:29 UTC, merged

2022-11-08 14:19 UTC, LeSnake04 commented
I think I found the issue: I accidentally deleted the require line when refactoring for the options.