feat: allow version specification for deno
topgrade-rs/topgrade pull request #970
Opened 2024-10-27 14:07 UTC by sehnryr

## What does this PR do
Add config field for specifying deno version.

## Standards checklist

- [x] The PR title is descriptive
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
- [ ] If this PR introduces new user-facing messages they are translated
 
## For new steps

- [ ] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

2024-10-27 23:47 UTC, SteveLauC commented
> Add config field for specifying deno version.

What was the previous behavior?

2024-10-28 01:06 UTC, sehnryr commented
> > Add config field for specifying deno version.
> 
> What was the previous behavior?

`deno upgrade`s to "stable" channel by default and overwrites any other version.

2024-10-28 01:51 UTC, SteveLauC commented
> and overwrites any other version.

Say I have all the 3 channels installed, `deno upgrade` will upgrade the "stable" channel to remove all the other installations? Or can I have 3 channels installed? (Rust allows you to do so, I am not sure about the case of Deno)

Stupid question, if I already have "1.45.0" installed, what will `deno upgrade 1.45` do?

2024-10-28 01:53 UTC, SteveLauC requested changes
Just one tiny issue

2024-10-28 01:53 UTC, SteveLauC commented on config.example.toml
> +# version = stable
```suggestion
# version = "stable"
```

If it should be a string

2024-10-28 09:52 UTC, sehnryr commented
> Say I have all the 3 channels installed, `deno upgrade` will upgrade the "stable" channel to remove all the other installations? Or can I have 3 channels installed? (Rust allows you to do so, I am not sure about the case of Deno)
> 
> Stupid question, if I already have "1.45.0" installed, what will `deno upgrade 1.45` do?

I don't think you can install multiple versions of Deno :thinking:.

`deno upgrade 1.45` won't work as it only recognize semver:
```
error: Invalid version passed (1.45)

Pass a semver, or a full 40 character git commit hash, or a release channel name.

Usage:
Latest
  deno upgrade

Specific version
  deno upgrade 1.45.0
  deno upgrade 1.46.0-rc.1
  deno upgrade 9bc2dd29ad6ba334fd57a20114e367d3c04763d4

Channel
  deno upgrade stable
  deno upgrade rc
  deno upgrade canary
```

And if we try upgrading to the same version, deno will recognize it and not replace it.

2024-10-28 09:58 UTC, sehnryr commented
I just found out there's an issue with deno's v1 `upgrade` arguments as they don't match with v2:
- v1: `deno upgrade [--version <version>]/[--canary]`
- v2: `deno upgrade [<version>]/[stable/rc/canary]`

2024-10-28 23:52 UTC, SteveLauC reviewed
Just some trivial comments, the impl looks generally good

2024-10-28 23:52 UTC, SteveLauC commented on src/steps/node.rs
> +                        return Err(SkipStep("Deno v1.x cannot be upgraded to a release candidate".to_string()).into());
Nit: this and line 225 are both called Deno v1.x, it might be better to make them different, e.g., `Deno (1.6.0-2.0.0)` and `Deno (1.0.0-1.6.0)`

2024-10-28 23:52 UTC, SteveLauC commented on src/steps/node.rs
> +                    "stable" => {}
Nit: To make it clear:

```suggestion
                    "stable" => { /* do nothing, as stable is the default channel to upgrade */ }
```

2024-10-28 23:52 UTC, SteveLauC commented on src/steps/node.rs
> +        let version_str = Command::new(&self.command)
Could you please add one example output of this command here, which would make the code easier to understand

2024-10-29 10:09 UTC, merged